# Generated by Django 3.2.15 on 2025-01-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
                ('d', models.FloatField()),
                ('e', models.FloatField()),
                ('f', models.FloatField()),
                ('g', models.FloatField()),
                ('h', models.FloatField()),
            ],
            options={
                'verbose_name': 'Коэффициент',
                'verbose_name_plural': 'Коэффициенты',
            },
        ),
        migrations.CreateModel(
            name='Ranges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tmin', models.FloatField()),
                ('Tmax', models.FloatField()),
                ('coefficients', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elements.coefficients', verbose_name='Коэффициенты')),
            ],
            options={
                'verbose_name': 'Диапазон',
                'verbose_name_plural': 'Диапазоны',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=2)),
                ('molar_mass', models.FloatField()),
                ('num_ranges', models.IntegerField()),
                ('ranges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elements.ranges', verbose_name='Ranges')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
            },
        ),
    ]
