# Generated by Django 3.2.15 on 2025-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='enthalpy',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='element',
            name='enthalpy_diff',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
