# Generated by Django 3.2.15 on 2025-01-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20250110_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='ranges',
        ),
        migrations.AddField(
            model_name='ranges',
            name='element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='elements.element', verbose_name='Диапазон для элемента'),
            preserve_default=False,
        ),
    ]
