# Generated by Django 3.2.15 on 2025-01-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0003_auto_20250110_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coefficients',
            name='h',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
