# Generated by Django 3.2.15 on 2025-01-10 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0004_alter_coefficients_h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranges',
            name='coefficients',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elements.coefficients', verbose_name='Коэффициенты'),
        ),
        migrations.AlterField(
            model_name='ranges',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='elements.element', verbose_name='Диапазон для элемента'),
        ),
    ]
